### ISSUE TITLE
"SCRIPT0: secure random number generation not supported by this browser use chrome, FireFox or Internet Explorer 11"

### ISSUE THREAD

**Issue by omryr** [ethereumjs/ethereumjs-wallet#15]
im getting this error when running in IE 11, did anyone encounter it? and if yes what was the solution? i am looking for a few hours now and kinda lost, would appreciate any help.
thanks!

**Comment by WoeOm** [comment]
https://github.com/WoeOm/ethereumjs-wallet-react-native

**Comment by bokub** [comment]
Not using [ethereumjs-wallet](https://github.com/ethereumjs/ethereumjs-wallet) but I guess if comes from [crypto-browserify/randombytes](https://github.com/crypto-browserify/randombytes) because the string is [here](https://github.com/crypto-browserify/randombytes/blob/master/browser.js#L4)

Please check my [comment](https://github.com/crypto-browserify/randombytes/issues/6)

**Comment by holgerd77** [comment]
Outdated, will close for now, please re-open if issue still occurs.
