### ISSUE TITLE
Minimal browser builds

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-wallet#8]
by supplying our own more minimal version of https://github.com/crypto-browserify/crypto-browserify
we can drop the following deps:

```
require('diffie-hellman')
require('browserify-sign')
require('create-ecdh')
require('public-encrypt')
```

bc we are only using

```
crypto.randomBytes
crypto.pbkdf2Sync
crypto.createCipheriv
crypto.createDecipheriv
```

we just need to make a more minimal crypto entrypoint https://github.com/crypto-browserify/crypto-browserify/blob/master/index.js
and sub it out with the browser field https://github.com/substack/node-browserify#browser-field

**Comment by tad88dev** [comment]
@kumavis I have tried to build my own browser version by using browserify. It's working damn slow.

**Comment by hitchcott** [comment]
@tad88dev same experience; `toV3` is taking around 20 seconds in Chromium

**Comment by axic** [comment]
@tad88dev @hitchcott I'm afraid that is an intentional parameter of using scrypt. The point of scrypt is to be CPU and memory hard. Using the C scrypt implementation it is >10 times faster though.

In the browser it should be run in a worker.

Alternatively you can try tweaking the scrypt parameters (https://github.com/ethereumjs/ethereumjs-wallet#remarks-about-tov3) with the risk of reducing security significantly. Some wallets (such as keythereum) use much lower iteration count and thus they are faster. etheruemjs-wallet uses the default settings used by geth.

**Comment by tad88dev** [comment]
@axic Agree, scrypt.js is slow down whole process. I have some "cheats" to speed up without change the scrypt parameters.
I have a table to lookup computed scrypt hash:
`sha-256(x) ----> scrypt(x)`

**Comment by hitchcott** [comment]
Thanks @axic, the webworker solution should be good enough. Perhaps it's worth adding to the docs.

**Comment by connectdotz** [comment]
has this problem ever resolved? can this library actually run in the browser with reasonable performance? According to [browserify](http://browserify.org/):

> Get browser versions of the node core libraries events, stream, path, url, assert, buffer, util, querystring, http, vm, and crypto when you require() them

Looks like the [code](https://github.com/ethereumjs/ethereumjs-wallet/blob/d5449dafcab2dda181cae89b8733e53b04cbec85/index.js#L2) is still using the node.js crypto, therefore wondering if this ever resolved?
